In [1]:
import numpy as np
import scipy.constants as constants
import math


In [2]:
class ChargedObject(object):
    
    def __init__(self, center):
        self.c = center

In [3]:
#A =ChargedObject(np.array([5,4,3]))

#A.c


In [4]:
#A=np.array([4,3])
#B=np.array([5,12])

#C= A+B
#D= A-B

#C,D

In [5]:
# Amag=np.linalg.norm(A)
# Bmag=np.linalg.norm(B)
# Cmag=np.linalg.norm(C)
# Dmag=np.linalg.norm(D)


# Amag**2, Bmag**2

In [6]:
class ChargedSphere(ChargedObject):

        
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.rho = distribution
    
            
    def E(self,x):
        if np.linalg.norm(x-self.c) == 0:
            E_Field = np.array([0,0,0])
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = (self.rho/constants.epsilon_0)*(np.linalg.norm(x-self.c)/3)
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**3)/(3*(np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        
        return E_Field*E_hat
    
    def V(self,x):
        pi = 3.14159
        q = self.rho*(4/3)*pi*((self.rad)^3)
        r_perp = np.linalg.norm(x-self.c)
        if r_perp == 0:
            raise ZeroDivisionError
        if r_perp < self.rad :
            V = (q/(8*pi*constants.epsilon_0*self.rad))*(3-(r_perp/self.rad)^2)
        if r_perp >= self.rad:
            V = q/(4*pi*constants.epsilon_0*r_perp)         
        return V    

In [7]:
V = 0
A = ChargedSphere(np.array([0,0,0]),1,.00000001)
#A.c, A.rad, A.rho
A.E(np.array([0,1,5]))

array([  0.        ,   2.83968386,  14.19841931])

In [8]:
A.V(np.array([0,0,100]))


7.5293937783876483

In [9]:
class ChargedSphereShell(ChargedObject):
    
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.sigma = distribution
        
                
    def E(self,x):
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = 0
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad**2)/((np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        return E_Field*E_hat
        
    def V(self,x):
        pi = 3.14159
        q = self.sigma*(4)*pi*((self.rad)^2)
        r_perp = np.linalg.norm(x-self.c)
        if np.linalg.norm(x-self.c) == 0:
            raise ZeroDivisionError
        if np.linalg.norm(x-self.c) < self.rad :
            V = q/(4*pi*constants.epsilon_0*self.rad)
        if np.linalg.norm(x-self.c) >= self.rad:
            V = q/(4*pi*constants.epsilon_0*r_perp)         
        return V

In [10]:
B = ChargedSphereShell(np.array([1,0,0]),1,.00000001)
B.V(np.array([100,20,100]))

23.838893326700571

In [11]:
class ChargedCylinderShell(ChargedObject):
    def __init__(self, center, axis, radius, distribution):
        self.c = center
        self.axis = axis
        self.rad = radius
        self.sigma = distribution


    def E(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))

        if r_perp <= self.rad :
            E_Field = 0
        if r_perp > self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad)/((r_perp)))
        return E_Field*E_hat

    
    def V(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        pi = 3.14159
        a = 1000 #This is an arbitrary choice
        
        if r_perp <= self.rad :
            V_field = (self.sigma/4*constants.epsilon_0)*(self.rad**2 -r_perp**2)
        if r_perp > self.rad :
            V_field = (self.sigma*self.rad/2*pi*constants.epsilon_0)*math.log(r_perp/a)
            
        return V_field

In [12]:
C = ChargedCylinderShell(np.array([0,-1,0]), np.array([0,1,0]),1,.000000001)
C.V(np.array([100,4,0]))

-3.202461585979198e-20

In [13]:
class ChargedCylinder(ChargedObject):
    
    def __init__(self,center, axis, radius, distribution) :
        self.c = center
        self.rad = radius
        self.axis = axis
        self.rho = distribution

    def E(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        if r_perp == 0 :
            return np.array([0,0,0])
        if 0 < r_perp <= self.rad :
            E_Field = (self.rho/constants.epsilon_0)*(r_perp/2)
        if r_perp > self.rad :
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**2)/(2*r_perp))
        
        return E_Field*E_hat
    
    def V(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        pi = 3.14159
        q = self.rho*pi*((self.rad)^2) 
        a = 1000 #this is an arbitrary reference choice and either 0 or infinity would lead to problems
        
        if r_perp <= self.rad:
            V_field = (self.rho/4*constants.epsilon_0)*(self.rad**2 - r_perp**2)
        if r_perp > self.rad:
            V_field = q/(2*pi*constants.epsilon_0)*math.log(r_perp/a)
        return V_field        


In [14]:
D = ChargedCylinder(np.array([0,0,0]), np.array([0,0,1]),1,.000000001)
D.V(np.array([1000,100,0]))

0.8428495412108394

In [15]:
class ChargedPlane(ChargedObject):
    
    def __init__(self,center, distribution,normal):
        class Infinite_Plane(object):
    
            self.normal = normal
            self.sigma = distribution
            self.c = center
                
    def E(self,x):
        E_Field = self.sigma/(2*constants.epsilon_0)
        if np.dot(x-self.c,self.normal) == 0:
            E_hat = np.array([0,0,0])
        if np.dot(x-self.c,self.normal) > 0:
            E_hat = self.normal/np.linalg.norm(self.normal)
        if np.dot(x-self.c,self.normal) < 0:
            E_hat = -self.normal/np.linalg.norm(self.normal)
        return E_Field*E_hat
        
    def V(self,x):
        a = 1000 #this is an arbitrary choice as infinity would cause problems.
        r_vec = (x -self.c)
        perp_distance = np.dot(self.normal,r_vec)
        V_field = np.linalg.norm(self.E(x))*(perp_distance-a)
        return V_field

In [16]:
J = ChargedPlane(np.array([0,0,0]),.000000000001,np.array([1,0,0]))
J.V(np.array([1000,0,0]))


0.0

In [17]:
List_of_Objects = [A,B,C,D,J]

In [18]:
Total_E = 0
for obj in List_of_Objects:
    Total_E += obj.E(np.array([7,2,1]))
    

In [19]:
Total_E

array([ 55.77992118,  12.63250689,   7.50959132])

In [20]:
#write a page or two to tell where the math comes from

In [21]:
def E_Superposition(List_of_Objects,x):
    Total_E = 0
    for obj in List_of_Objects:
        Total_E += obj.E(x)
    return Total_E

In [22]:
EFIELD = E_Superposition(List_of_Objects, np.array([7,2,1]))
EFIELD

array([ 55.77992118,  12.63250689,   7.50959132])

In [23]:
def V_Superposition(List_of_Objects,x):
    Total_V = 0
    for obj in List_of_Objects:
        Total_V += obj.V(x)
    return Total_V

In [24]:
VFIELD = V_Superposition(List_of_Objects, np.array([7,7,7]))
VFIELD

-483.15494561619806

In [42]:
def Sweep(List_of_Objects,x_range,y_range,z_range):
    Xpoints = list(range(x_range[0],x_range[1]+1))
    Ypoints = list(range(y_range[0],y_range[1]+1))
    Zpoints = list(range(z_range[0],z_range[1]+1))
    I = len(Xpoints)
    J = len(Ypoints)
    K = len(Zpoints)
    NumElements = I*J*K*4
    Array = np.array(range(NumElements))
    DataTensor = Array.reshape(I,J,K,4)
    for i in range(0,I):
        x = Xpoints[i]
        for j in range(0,J):
            y = Ypoints[j]
            for k in range(0,K):
                z = Zpoints[k]
                E = E_Superposition(List_of_Objects,[x,y,z])
                V = V_Superposition(List_of_Objects,[x,y,z])
                DataTensor[i,j,k,:] = [E[0],E[1],E[2],V]
    return DataTensor

In [43]:
Sweep(List_of_Objects,[-10,10],[-10,10],[-10,10])

/userspace/l/lgmcquown/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py:14: RuntimeWarning: invalid value encountered in true_divide
/userspace/l/lgmcquown/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py:29: RuntimeWarning: invalid value encountered in true_divide


ValueError: cannot convert float NaN to integer

In [31]:
Array = np.array(range(64))
Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
Brray =Array.reshape(2,2,4,2,2)
Brray

In [36]:
I=5
J=5
K=5
NumElements = I*J*K*4
Array = np.array(range(NumElements))
#Array
DataTensor = Array.reshape(I,J,K,4)
DataTensor

array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11],
         [ 12,  13,  14,  15],
         [ 16,  17,  18,  19]],

        [[ 20,  21,  22,  23],
         [ 24,  25,  26,  27],
         [ 28,  29,  30,  31],
         [ 32,  33,  34,  35],
         [ 36,  37,  38,  39]],

        [[ 40,  41,  42,  43],
         [ 44,  45,  46,  47],
         [ 48,  49,  50,  51],
         [ 52,  53,  54,  55],
         [ 56,  57,  58,  59]],

        [[ 60,  61,  62,  63],
         [ 64,  65,  66,  67],
         [ 68,  69,  70,  71],
         [ 72,  73,  74,  75],
         [ 76,  77,  78,  79]],

        [[ 80,  81,  82,  83],
         [ 84,  85,  86,  87],
         [ 88,  89,  90,  91],
         [ 92,  93,  94,  95],
         [ 96,  97,  98,  99]]],


       [[[100, 101, 102, 103],
         [104, 105, 106, 107],
         [108, 109, 110, 111],
         [112, 113, 114, 115],
         [116, 117, 118, 119]],

        [[120, 121, 122, 123],
         [124, 125, 126, 