In [44]:
import numpy as np
import scipy.constants as constants
import scipy.integrate as integrate


In [45]:
class ChargedObject(object):
    
    def __init__(self, center):
        self.c = center

In [46]:
#A =ChargedObject(np.array([5,4,3]))

#A.c


In [47]:
#A=np.array([4,3])
#B=np.array([5,12])

#C= A+B
#D= A-B

#C,D

In [48]:
# Amag=np.linalg.norm(A)
# Bmag=np.linalg.norm(B)
# Cmag=np.linalg.norm(C)
# Dmag=np.linalg.norm(D)


# Amag**2, Bmag**2

In [68]:
class ChargedSphere(ChargedObject):

        
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.rho = distribution
    
            
    def E_Sphere(self,x):
        if np.linalg.norm(x-self.c) == 0:
            raise ZeroDivisionError
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = (self.rho/constants.epsilon_0)*(np.linalg.norm(x-self.c)/3)
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**3)/(3*(np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        
        return E_Field*E_hat
    
    
    def V_field(self,x):
        V = 0
        for num in range(3):
            integrand = self.E_Sphere(x)[num]
            V += integrate.quad(integrand,self.c[num],x[num], args = x)
        return V
            

In [69]:
V = 0
A = ChargedSphere(np.array([1,1,1]),2,.00000001)
#A.c, A.rad, A.rho
A.E_Sphere(np.array([0,0,0]))

array([-376.46968892, -376.46968892, -376.46968892])

In [70]:
A.V_field(np.array([0,0,0]))


error: quad: first argument is not callable

In [10]:
class ChargedSphereShell(ChargedObject):
    
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.sigma = distribution
        
                
    def E_Sphere_Shell(self,x):
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = 0
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad**2)/((np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        
        return E_Field*E_hat

In [11]:
# B = ChargedSphereShell(np.array([1,1,1]),2,.00000001)
# B.E_Sphere_Shell(np.array([3,1,0]))

array([ 808.13934326,    0.        , -404.06967163])

In [35]:
class ChargedCylinderShell(ChargedObject):
    def __init__(self, center, axis, radius, distribution):
        self.c = center
        self.axis = axis
        self.rad = radius
        self.sigma = distribution

        
    def E_Cylinder_Shell(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad :
            E_Field = 0
        if r_perp > self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad)/((r_perp)))
         
        
        return E_Field*E_hat

In [40]:
# C = ChargedCylinderShell(np.array([0,0,0]), np.array([1,1,0]),1,.000000001)
# C.E_Cylinder_Shell(np.array([5,4,0]))

array([ 0., -0.,  0.])

In [41]:
class ChargedCylinder(ChargedObject):
    
    def __init__(self,center, axis, radius, distribution) :
        self.c = center
        self.rad = radius
        self.axis = axis
        self.sigma = sigma
                
    def E_Cylinder(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad :
            E_Field = (self.rho/constants.epsilon_0)*(r_perp/2)
        if r_perp > self.rad:
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**2)/(2*r_perp))
        

        E_hat = r_vec - (axis_hat*r_parallel)
        
        return E_Field*E_hat
    

In [42]:
# D = ChargedCylinderShell(np.array([0,0,0]), np.array([1,0,0]),2,.000000001)
# D.E_Cylinder_Shell(np.array([1,1,0]))

array([ 0.,  0.,  0.])

In [43]:
class ChargedPlane(ChargedObject):
    
    def __init__(self,center, distribution,normal):
        class Infinite_Plane(object):
    
            self.normal = normal
            self.sigma = distribution
            self.c = center
        
        
    def E_Plane(self,sigma):
        E_Field = self.sigma/(2*constants.epsilon_0)
        
        E_hat = self.normal/np.linalg.norm(self.normal)
        
        return E_Field*E_hat
        