In [48]:
import numpy as np
import scipy.constants as constants
import math


In [49]:
class ChargedObject(object):
    
    def __init__(self, center):
        self.c = center

In [50]:
#A =ChargedObject(np.array([5,4,3]))

#A.c


In [51]:
#A=np.array([4,3])
#B=np.array([5,12])

#C= A+B
#D= A-B

#C,D

In [52]:
# Amag=np.linalg.norm(A)
# Bmag=np.linalg.norm(B)
# Cmag=np.linalg.norm(C)
# Dmag=np.linalg.norm(D)


# Amag**2, Bmag**2

In [53]:
class ChargedSphere(ChargedObject):

        
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.rho = distribution
    
            
    def E(self,x):
        if np.linalg.norm(x-self.c) == 0:
            raise ZeroDivisionError
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = (self.rho/constants.epsilon_0)*(np.linalg.norm(x-self.c)/3)
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**3)/(3*(np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        
        return E_Field*E_hat
    
    def V(self,x):
        if np.linalg.norm(x-self.c) == 0:
            raise ZeroDivisionError
        if np.linalg.norm(x-self.c) < self.rad :
            V = (self.rho/6*constants.epsilon_0)*(3 - ((np.linalg.norm(x-self.c)**2)/self.rad**2))
        if np.linalg.norm(x-self.c) >= self.rad:
            V = (self.rho*((self.rad)^3)/((3*constants.epsilon_0)*(np.linalg.norm(x-self.c))))         
        return V    

In [54]:
V = 0
A = ChargedSphere(np.array([0,0,0]),1,.00000001)
#A.c, A.rad, A.rho
A.E(np.array([0,1,5]))

array([  0.        ,   2.83968386,  14.19841931])

In [55]:
A.V(np.array([0,0,1]))


752.93937783876481

In [56]:
class ChargedSphereShell(ChargedObject):
    
    def __init__(self,center,radius,distribution):
        self.c = center
        self.rad = radius
        self.sigma = distribution
        
                
    def E(self,x):
        if np.linalg.norm(x-self.c) < self.rad :
            E_Field = 0
        if np.linalg.norm(x-self.c) >= self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad**2)/((np.linalg.norm(x-self.c)**2)))
        
        E_hat = (x-self.c)/np.linalg.norm(x-self.c)
        return E_Field*E_hat
        
    def V(self,x):
        if np.linalg.norm(x-self.c) == 0:
            raise ZeroDivisionError
        if np.linalg.norm(x-self.c) < self.rad :
            V = (self.sigma/6*constants.epsilon_0)*(3 - ((np.linalg.norm(x-self.c)**2)/self.rad**2))
        if np.linalg.norm(x-self.c) >= self.rad:
            V = (self.sigma*((self.rad)^3)/((3*constants.epsilon_0)*(np.linalg.norm(x-self.c))))         
        return V

In [72]:
B = ChargedSphereShell(np.array([1,0,0]),1,.00000001)
B.V(np.array([3,1,0]))

336.72472635677536

In [58]:
class ChargedCylinderShell(ChargedObject):
    def __init__(self, center, axis, radius, distribution):
        self.c = center
        self.axis = axis
        self.rad = radius
        self.sigma = distribution

        
    def E(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad :
            E_Field = 0
        if r_perp > self.rad:
            E_Field = (self.sigma/constants.epsilon_0)*((self.rad)/((r_perp)))
        return E_Field*E_hat
    
    def V(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad :
            V_field = 0
        if r_perp > self.rad :
            V_field = (self.sigma*self.rad/constants.epsilon_0)*math.log(r_perp/self.rad)
            
        return V_field

In [59]:
C = ChargedCylinderShell(np.array([0,-1,0]), np.array([0,1,0]),1,.000000001)
C.V(np.array([5,4,0]))

181.7713770687378

In [60]:
class ChargedCylinder(ChargedObject):
    
    def __init__(self,center, axis, radius, distribution) :
        self.c = center
        self.rad = radius
        self.axis = axis
        self.sigma = sigma
                
    def E(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad:
            E_Field = (self.rho/constants.epsilon_0)*(r_perp/2)
        if r_perp > self.rad:
            E_Field = (self.rho/constants.epsilon_0)*((self.rad**2)/(2*r_perp))
        E_hat = r_vec - (axis_hat*r_parallel)
        
        return E_Field*E_hat
    
    def V(self,x):
        axis_hat = self.axis/np.linalg.norm(self.axis)
        r_vec = x-self.c
        r_parallel = np.dot(axis_hat,r_vec)
        E_not_hat = (r_vec - (axis_hat*r_parallel))
        E_hat = E_not_hat/np.linalg.norm(E_not_hat)
        r_perp = np.linalg.norm(np.cross(axis_hat,r_vec))
        
        if r_perp <= self.rad:
            V_field = (self.rho/4*constants.epsilon_0)*((r_perp)^2)
        if r_perp > self.rad:
            V_field = (self.rho/(2*constants.epsilon_0))*((self.rho**2))*math.log(r_perp/self.R)
        return V_field
    

In [74]:
D = ChargedCylinderShell(np.array([0,1,0]), np.array([0,1,0]),1,.000000001)
D.V(np.array([1,1,7]))

220.91371258485026

In [76]:
class ChargedPlane(ChargedObject):
    
    def __init__(self,center, distribution,normal):
        class Infinite_Plane(object):
    
            self.normal = normal
            self.sigma = distribution
            self.c = center
        
        
    def E(self,sigma):
        E_Field = self.sigma/(2*constants.epsilon_0)
        E_hat = self.normal/np.linalg.norm(self.normal)
        return E_Field*E_hat
        
    def V(self,x):
        r_vec = (x -self.c)
        perp_distance = np.dot(self.normal,r_vec)
        V_field = -np.linalg.norm(self.E(self.sigma))*perp_distance
        return V_field

In [77]:
E = ChargedPlane(np.array([1,2,1]),.000000000001,np.array([1,0,0]))

In [78]:
List_of_objects = [A,B,C,D,E]

In [79]:
Total_E = 0
for obj in List_of_objects:
    Total_E += obj.E(np.array([7,2,1]))
    

In [80]:
Total_E

array([ 64.13328635,  10.50154638,   9.76840946])

In [81]:
#write a page or two to tell where the math comes from

In [82]:
def E_Superposition(List_of_objects,x):
    Total_E = 0
    for obj in List_of_objects:
        Total_E += obj.E(x)
    return Total_E

In [83]:
EFIELD = E_Superposition(List_of_objects, np.array([7,2,1]))
EFIELD

array([ 64.13328635,  10.50154638,   9.76840946])

In [84]:
def V_Superposition(List_of_objects,x):
    Total_V = 0
    for obj in List_of_objects:
        Total_V += obj.V(x)
    return Total_V

In [86]:
VFIELD = V_Superposition(List_of_objects, np.array([7,7,7]))
VFIELD

644.63701010056946