In [2]:
import Charged_Objects as obj
import numpy as np

In [3]:
A = obj.ChargedSphere(np.array([0,0,0]),1,.00000001)
B = obj.ChargedSphereShell(np.array([1,0,0]),1,.00000001)
C = obj.ChargedCylinder(np.array([0,-1,0]), np.array([0,1,0]),1,.000000001)
D = obj.ChargedCylinderShell(np.array([0,1,0]), np.array([0,1,0]),1,.000000001)
E = obj.ChargedPlane(np.array([1,2,1]),.000000000001,np.array([1,0,0]))

In [4]:
List_of_Objects = [A,B,C,D,E]

In [5]:
EFIELD = obj.E_Superposition(List_of_Objects, np.array([7,2,100]))
EFIELD

array([ 0.18383063,  0.00299233,  1.8354692 ])

In [6]:
VFIELD = obj.V_Superposition(List_of_Objects, np.array([100,100,100]))
VFIELD

-358.27620594302778

In [28]:
DataArray = obj.Sweep_Points(List_of_Objects,[5,10],[5,10],[5,10])
DataArray

array([[[[  28,   13,   30, -391],
         [  22,   10,   29, -410],
         [  18,    8,   27, -429],
         [  15,    6,   26, -445],
         [  12,    5,   24, -458],
         [  10,    4,   22, -470]],

        [[  26,   12,   27, -427],
         [  21,   10,   27, -440],
         [  17,    8,   26, -452],
         [  14,    7,   24, -464],
         [  12,    5,   23, -474],
         [  10,    4,   21, -483]],

        [[  24,   11,   25, -462],
         [  20,   10,   25, -469],
         [  16,    8,   24, -476],
         [  13,    7,   23, -483],
         [  11,    5,   21, -490],
         [   9,    4,   20, -496]],

        [[  22,   10,   23, -493],
         [  18,    9,   23, -496],
         [  15,    8,   23, -499],
         [  13,    6,   22, -503],
         [  11,    5,   20, -506],
         [   9,    4,   19, -510]],

        [[  21,    9,   22, -522],
         [  18,    8,   22, -521],
         [  15,    7,   21, -521],
         [  12,    6,   21, -521],
         [  

In [8]:
# WORK = obj.ChargedCylinder(np.array([0,0,0]), np.array([1,1,0]),1,.000000001)
# DoIt = WORK.E(np.array([1,1,2]))
# Ehat = DoIt/np.linalg.norm(DoIt)
# exp = np.array([0,0,1])
# np.testing.assert_almost_equal(Ehat,exp, decimal = 10)

In [13]:
# X,Y = list(range(5,10+1)), list(range(5,10+1))


In [26]:
# DataArray[1,4,3,0:3]

array([13,  5, 18])

In [ ]:
# def PlotSlice(DataArray,axis,constant):
#     streamplot()
    